package:
  name: speclite
  version: 0.5

source:
  fn: speclite-0.5.tar.gz
  url: https://pypi.python.org/packages/39/ac/d7ce5d518d32e4c84ecc1047c8a0d8ef8a6e934ee543e34c4f3cfdca6631/speclite-0.5.tar.gz#md5=2d70a458cff13dc502f39c31c4b4470d

requirements:
  build:
    - python >=3.5,<3.6
    - setuptools
    - pyyaml
    - numpy
    - scipy
    - astropy 1.3.3
    - matplotlib
    - astropy-helpers 1.3.1

  run:
    - python >=3.5,<3.6
    - setuptools
    - pyyaml
    - numpy
    - scipy
    - astropy 1.3.3
    - matplotlib
    - astropy-helpers 1.3.1

about:
  home: http://speclite.readthedocs.io
  license: BSD
  summary: Lightweight utilities for working with spectroscopic data.
