package:
  name: harp
  version: 1.0.4

source:
  fn: harp-1.0.4.tar.bz2
  url: https://github.com/tskisner/HARP/releases/download/v1.0.4/harp-1.0.4.tar.bz2

requirements:
  build:
    - python >=3.5,<3.6
    - cfitsio 3.41
    - mkl
    - numpy
    - boost 1.61.0

  run:
    - python >=3.5,<3.6
    - cfitsio 3.41
    - mkl
    - numpy
    - boost 1.61.0

about:
  home: https://github.com/tskisner/HARP
  license: BSD
  summary: High performance Astrophysics Reduction and Processing
