package:
  name: fitsio
  version: 0.9.12rc1

source:
  fn: fitsio-0.9.12rc1.tar.gz
  url: https://github.com/esheldon/fitsio/archive/v0.9.12rc1.tar.gz

build:
  number: 0

requirements:
  build:
    - python >=3.5,<3.6
    - cfitsio
    - setuptools
    - numpy

  run:
    - python >=3.5,<3.6
    - cfitsio
    - setuptools
    - numpy

about:
  home: https://github.com/esheldon/fitsio
  license: GPL
  summary: A python package for FITS input/output wrapping cfitsio.

