package:
  name: fftw
  version: 3.3.5

source:
  fn: fftw-3.3.5.tar.gz
  url: http://www.fftw.org/fftw-3.3.5.tar.gz

build:
  number: 0

about:
  home: http://www.fftw.org/
  license: GPL
  summary: |
    C subroutine library for computing the discrete Fourier transform (DFT) 
    in one or more dimensions, of arbitrary input size, and of both real and 
    complex data (as well as of even/odd data, i.e. the discrete cosine/sine 
    transforms or DCT/DST).
