package:
  name: cfitsio
  version: 3.41

source:
  fn: cfitsio3410.tar.gz
  url: http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio3410.tar.gz

about:
  home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  license: GPL
  summary: |
    A library of C and Fortran subroutines for reading and writing 
    data files in FITS (Flexible Image Transport System) data format.
