package:
  name: astropy-helpers
  version: 1.3.1

source:
  fn: astropy-helpers-1.3.1.tar.gz
  url: https://pypi.python.org/packages/b0/f0/1e37292b9e694f02949a239c095afa1f63978f5e47d5586547514092b183/astropy-helpers-1.3.1.tar.gz#md5=48e4fade3a02cfc73b72336b03cdda56

requirements:
  build:
    - python >=3.5,<3.6
    - setuptools

  run:
    - python >=3.5,<3.6
    - setuptools

about:
  home: https://pypi.org/project/astropy-helpers/
  license: BSD
  summary: Utilities for building and installing Astropy, Astropy affiliated packages, and their respective documentation.
